build:
	pdflatex solution.tex
	bibtex solution
	pdflatex solution.tex

clean:
	rm -f *.aux
	rm -f *.log
	rm -f *.out
	rm -f solution-blx.bib
	rm -f *.bbl
	rm -f *.bcf
	rm -f *.blg
	rm -f *.run.xml
	rm -f texput.log

