build:
	pdflatex article.tex
	bibtex article
	pdflatex article.tex

clean:
	rm -f *.aux
	rm -f *.log
	rm -f *.out
	rm -f article-blx.bib
	rm -f *.bbl
	rm -f *.bcf
	rm -f *.blg
	rm -f *.run.xml
	rm -f texput.log

